#!/usr/bin/env python
# encoding: utf-8
import sys

def configure(conf):
    pass

def build(bld):
    lv2_base = 'gx_fuzz'

    if sys.platform != 'darwin' or any('clang' not in s for s in bld.env["CXX"]):
        compile_flags = ['-Wl,-z,noexecstack','-Wl,-z,relro,-z,now','-Wl,--exclude-libs,ALL']
    else:
        compile_flags = []

    bld.lv2(
        lv2_base = lv2_base,
        source   = ['gx_fuzz.cpp'],
        includes = ['../faust','./', '../DSP', '../DSP/tube_tables'],
        cxxflags=['-fvisibility=hidden'] + compile_flags,
        use = ['LV2CORE','ZITA_RESAMPLER'],
        )
    bld.lv2_gui(
        lv2_base = lv2_base,
        source   = ' gx_fuzz_ui.cpp',
        includes = ['../xputty/header','../xputty/header/widgets','../xputty/resources',],
        cxxflags=['-fvisibility=hidden'] + compile_flags,
        use = ['xcairo','X11', 'CAIRO','LV2CORE'],
        )
